export default {
    'news': require('./news.png'),
    'deals': require('./deals.png'),
    'pulse': require('./pulse.png'),
    'sound': require('./sound.png'),
    'like': require('./like.png'),
    'gift': require('./gift.png'),
    'comment': require('./comment.png'),
    'more': require('./more.png'),
    'share': require('./share.png'),
    'gifts': require('./gifts.png'),
    'discover': require('./discover.png'),
    'drawer': require('./drawer.png'),
    'bookings': require('./bookings.png'),
    'search': require('./search.png'),
    'points': require('./points.png'),
    'rating': require('./rating.png'),
    'pin': require('./pin.png'),
    'heartFilled': require('./heart-filled.png'),
    'heartOutlined': require('./heart-outlined.png'),
}